spring.application.name=ReviewService
spring.datasource.url=jdbc:postgresql://localhost:5432/RKMS_Review
spring.datasource.username=postgres
spring.datasource.password=Viha@1812
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}