spring.application.name=PaperService
server.port=8083
file.upload-dir=uploads
spring.datasource.url=jdbc:postgresql://localhost:5432/RKMSNEW
spring.datasource.username=postgres
spring.datasource.password=560050
spring.jpa.hibernate.ddl-auto=update
user-service.url=${USER_SERVICE_URL:http://localhost:8081}
notification-service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8084}
review-service.url=${REVIEW_SERVICE_URL:http://localhost:8085}
report-service.url=${REPORT_SERVICE_URL:http://localhost:8086}
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}