spring.application.name=AuthServiceD
server.port=8082
jwt.secret=${RKMS_JWT_SECRET:ClarivateSecretKey12345678901234567890}
jwt.expiration-millis=${JWT_EXPIRATION_MILLIS:3600000}
user.service.url=${USER_SERVICE_URL:http://localhost:8081}
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}
