spring.application.name=ReportService
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/RKMS_Report
spring.datasource.username=postgres
spring.datasource.password=Viha@1812
spring.jpa.hibernate.ddl-auto=update

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}
