spring.application.name=userservice
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/RKMSNEW
spring.datasource.username=postgres
spring.datasource.password=560050
spring.jpa.hibernate.ddl-auto=update
