spring.application.name=userservice
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/RKMS
spring.datasource.username=postgres
spring.datasource.password=Viha@1812
spring.jpa.hibernate.ddl-auto=update
