spring.application.name=userservice
spring.datasource.url=jdbc:postgresql://localhost:5432/RKMS
spring.datasource.username=postgres
spring.datasource.password=560050
spring.jpa.hibernate.ddl-auto=update