spring.application.name=notificationservice
spring.datasource.url=jdbc:postgresql://localhost:5432/RKMS
spring.datasource.username=postgres
spring.datasource.password=560050
spring.jpa.hibernate.ddl-auto=update

server.port=8084

logging.level.root=INFO
logging.level.com.rkms.notificationservice=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html